name: servant-pubsub-webhook
ghc-options:
    - -Wall
library:
  exposed-modules:
    Servant.PubSub.Webhook
  source-dirs:
    - src
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
    dependencies:
      - hspec
      - servant-pubsub-webhook
      - here
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
      - bytestring
      - unordered-containers
dependencies:
  - base
  - servant
  - servant-server
  - servant-client
  - either
  - text
  - http-client
  - transformers
  - aeson
  - aeson-casing
  - wai
  - warp
  - transformers
  - wai-logger

